### PR TITLE
Fixed data decoding for 'Digilent PmodMAXSONAR'

### LINKED ISSUE #42: Data decoding for pmod_maxsonar is wrong
### Versions

* OS: Ubuntu 16.04
* GRiSP Toolchain: fd301290f8826d058313805e7aa764a405f905d6 (Nov 13, 2018)
* Erlang: 21.1
* Rebar: rebar 3.7.5+build.4233.reff564d16 on Erlang/OTP 21 Erts 10.1

### Description

The call 'pmod_maxsonar' constantly returns 'undefined' when fetching a value via get/0

### PR DESCRIPTION
**Pull request by aytchell**
The pattern for matching the data returned by the pmod is
wrong. According to the reference manual (
https://reference.digilentinc.com/_media/reference/pmod/pmodmaxsonar/pmodmaxsonar_rm.pdf
) there is only one 'R'-character in front of the sent distance.

I tested this fix during a GRiSP tutorial session on 06.12.2018:
 - old behavior was that 'undefined' was returned
 - new behavior is that reasonable distances (in inch) are returned

This commit fixes #42

### CODE REVIEW

File: src/pmod_maxsonar.erl [hunk 1]
```diff
@@ -45,9 +45,13 @@ handle_cast(Request, _State) -> error({unknown_cast, Request}).
 % @private
 handle_info({Port, {data, Data}}, #state{port = Port} = State) ->
     case Data of
-        <<_, _, D1, D2, D3, 10>> when $0 =< D1, D1 =< $9,
+        % Format of response is 'Rxxx\n' where xxx is the decimal
+        % representation of the measured range in inches (2.54cm)
+        % (left-padded with zeros - so there are always three digits)
+        <<82, D1, D2, D3, 10>> when $0 =< D1, D1 =< $9,
```
Comment (eproxus) [inline src/pmod_maxsonar.erl]: Could you change this to `<<$R, D1, D2, D3, $\n>>` instead? Matches better with the comment 😄

Comment (aytchell) [reply src/pmod_maxsonar.erl]: Done.
(Learned something new about erlang :blush:)
